"""
Django settings for Loading_Computer project.
Generated by 'django-admin startproject' using Django 4.2.x
"""

from pathlib import Path
import os
import pymysql
from dotenv import load_dotenv

# -----------------------------------------------------------------------------
# Base paths & .env
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env")

# -----------------------------------------------------------------------------
# Core security & debug
# -----------------------------------------------------------------------------
pymysql.install_as_MySQLdb()

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "replace-this-in-production")

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    "3.109.153.20",
    "marine-ops.com",
    "www.marine-ops.com",
    "localhost",
    "127.0.0.1",
]

# -----------------------------------------------------------------------------
# CORS / CSRF (React front-end & desktop shell)
# -----------------------------------------------------------------------------
from corsheaders.defaults import default_headers

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://marine-ops.com",
    "https://www.marine-ops.com",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:8765",
    "http://localhost:8765",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://marine-ops.com",
    "https://www.marine-ops.com",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:8765",
    "http://localhost:8765",
]

if DEBUG:
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    CSRF_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "auth-key",
    "x-csrftoken",
]

# -----------------------------------------------------------------------------
# Apps & middleware
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "corsheaders",
    "whitenoise.runserver_nostatic",  # runserver defers static to WhiteNoise

    # Local apps
    "Intact_Stability",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # <- right after SecurityMiddleware
    "corsheaders.middleware.CorsMiddleware",        # keep high, before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Loading_Computer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Loading_Computer.wsgi.application"

# -----------------------------------------------------------------------------
# Database
# - Default: MySQL (your current values)
# - Desktop/offline: set DJANGO_USE_SQLITE=1 to switch to SQLite file
# -----------------------------------------------------------------------------
USE_SQLITE = os.getenv("DJANGO_USE_SQLITE", "0").lower() in {"1", "true", "yes", "on"}

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("MYSQL_DB", "intact_stability_db3"),
            "USER": os.getenv("MYSQL_USER", "root"),
            "PASSWORD": os.getenv("MYSQL_PASSWORD", "Melvin@123"),
            "HOST": os.getenv("MYSQL_HOST", "localhost"),
            "PORT": os.getenv("MYSQL_PORT", "3306"),
            "OPTIONS": {
                "init_command": "SET default_storage_engine=INNODB",
            },
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        }
    }

# -----------------------------------------------------------------------------
# Password validation
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------------------------------------------
# I18N / TZ
# -----------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# Static & media (with WhiteNoise)
# -----------------------------------------------------------------------------
STATIC_URL = "/static/"

# Where collectstatic puts files
STATIC_ROOT = BASE_DIR / "staticfiles"

# IMPORTANT:
# - Keep your own project static directory (`static/`) if you use it.
# - Add the React build *static* folder so fonts/js/css are discoverable.
#   (Assumes you copied `front-end/build` to `Loading_Computer/frontend_build`)
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "frontend_build" / "static",   # <-- React build/static
]

# WhiteNoise: compressed & hashed files for production/desktop
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -----------------------------------------------------------------------------
# Upload limits
# -----------------------------------------------------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
APPEND_SLASH = False

# -----------------------------------------------------------------------------
# Email (env-based; console in DEBUG unless overridden)
# -----------------------------------------------------------------------------
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.zeptomail.in")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes", "on"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in {"1", "true", "yes", "on"}
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "emailapikey")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@marine-ops.com")

if DEBUG and os.getenv("FORCE_SMTP_IN_DEBUG", "0").lower() not in {"1", "true", "yes", "on"}:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
