# Generated by Django 5.0.3 on 2024-12-09 04:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cargo_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('MESHFILE', models.BinaryField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj'])])),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARGO_NAME', models.CharField(max_length=255)),
                ('WEIGHT', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('LENGTH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('BREADTH', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('HEIGHT', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('DIAMETER', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('X1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('X2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Y1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Y2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Z1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Z2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('COLOR', models.CharField(blank=True, max_length=255, null=True)),
                ('MESH', models.CharField(blank=True, max_length=255, null=True)),
                ('MESHFILE', models.BinaryField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj'])])),
                ('LCG', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('VCG', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('TCG', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pickle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.BinaryField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickle',
            },
        ),
        migrations.CreateModel(
            name='saved_data_cargo_and_tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('datas', models.JSONField()),
                ('pickle_name', models.CharField(max_length=255)),
                ('report', models.JSONField(blank=True, null=True)),
                ('jackup_data', models.JSONField()),
                ('crane_data', models.JSONField()),
                ('lcg_value', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_data_cargo_and_tank',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
