# Generated by Django 5.0.3 on 2025-03-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Intact_Stability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickle",
            name="vessel_type",
            field=models.CharField(default="C", max_length=20),
            preserve_default=False,
        ),
    ]
