# Generated by Django 5.0.3 on 2025-03-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intact_Stability', '0003_userauthkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthkey',
            name='one_timep',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
